toolchain = 'avr'
has-linker = false
c_flags = [
	'-Os',
    '-fpack-struct',
    '-fshort-enums',
	'-ffunction-sections',
	'-fdata-sections',
]
ld_flags = [
	'-fdata-sections',
	'-ffunction-sections',
	'-Wl,--gc-sections',
]
source = [
	'boot.c',
	'usb.c',
	'usb_descriptors.c',
]

[dependencies]
lufa = {}
