toolchain = 'arm-none-eabi'
c_flags = [
	'-Os',
	'-nostdlib',
	'-nostartfiles',
	'-ffunction-sections',
	'-fdata-sections',
	'-mthumb',
	'-mcpu=cortex-m4',
	'-mfloat-abi=hard',
	'-mfpu=fpv4-sp-d16',
	'-ffreestanding',
]
ld_flags = [
	'-mthumb',
	'-mcpu=cortex-m4',
	'-mfloat-abi=hard',
	'-mfpu=fpv4-sp-d16',
	'-lm',
	'-lc',
	'-lgcc',
	'-lnosys',
	'-nostdlib',
	'-nostartfiles',
	'-fdata-sections',
	'-ffunction-sections',
	'--specs=nano.specs',
	'--specs=nosys.specs',
	'-Wl,--gc-sections',
]
source = [
	'startup.c',
	'emu.c',
	'cmu.c',
	'systick.c',
	'gpio.c',
	'usb.c',
	'usb_descriptors.c',
	'hal/hid.c',
	'driver/key_direct.c',
]

[dependencies]
cmsis-5 = {}
tinyusb = { target = 'silabs/efm32' }
